FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY common-transacao-lib ./common-transacao-lib
RUN mvn -f ./common-transacao-lib/pom.xml clean install

COPY transacao-producer-api/pom.xml .
COPY transacao-producer-api/src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]